version: "3.9"

services:

  # A sample django project that has installed collectivo.
  collectivo:
    container_name: collectivo-app
    restart: "no"
    build:
      context: .
    ports:
      - "8000:8000"
    # Synchronize source code inside and outside the docker container.
    # The collectivo app is placed inside the test app (see Dockerfile).
    volumes:
      - ./collectivo_app:/collectivo_app
      - ./collectivo:/collectivo_app/collectivo
      - ./docker/static:/collectivo_app/static
    # Wait for database to be ready (this command will work only on linux),
    # migrate the database changes and start a development server.
    command: > #
      sh -c "while ! nc -z collectivo-db 5432; do sleep 1; done &&
             while ! nc -z keycloak 8080; do sleep 1; done &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DB_HOST: collectivo-db
      DB_NAME: collectivo_db
      DB_USER: admin
      DB_PASS: badpassword
      SECRET_KEY: badkey
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_CLIENT_SECRET_KEY: '**********'
      COLLECTIVO_EXTENSIONS: members
      COLLECTIVO_SETTINGS: collectivo_extensions.settings
      DEBUG: 1
      DEVELOPMENT: 1
      # ALLOWED_HOSTS
      # LANGUAGE_CODE
      # TIME_ZONE
      # KEYCLOAK_CLIENT_ID: collectivo
      # KEYCLOAK_REALM_NAME: collectivo
    depends_on:
      - collectivo-db
      - keycloak

  # A static files server for django
  collectivo-static:
    container_name: collectivo-static
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./docker/static:/app/static
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./docker/nginx/error.html:/usr/share/nginx/html/index.html
    restart: always

  # A PostgreSQL database.
  collectivo-db:
    container_name: collectivo-db
    image: postgres:14-alpine
    volumes:
      - collectivo-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: collectivo_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: badpassword

  # A frontend web application.
  collectivo-ux:
    container_name: collectivo-ux
    build: https://github.com/MILA-Wien/collectivo-ux.git#main
    restart: always
    environment:
      VITE_APP_API: http://collectivo.local:8000
      VITE_KEYCLOAK_URL: http://keycloak.local:8080
    ports:
      - "8001:80"

  # Keycloak for authentication.
  keycloak:
    build: ./docker/keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin  # UNSAFE DO NOT USE IN PRODUCTION
      KEYCLOAK_FRONTEND_URL: http://keycloak:8080
      ROOT_LOGLEVEL: ALL
      KEYCLOAK_LOGLEVEL: DEBUG
    volumes:
      - ./docker/keycloak/import:/opt/keycloak/data/import:ro
      - ./docker/keycloak/export:/tmp/export
    command:
      start-dev --import-realm
    ports:
      - "8080:8080"

volumes:
  collectivo-db-data:
